export const products  =[{"product_id":1,"product_name":"Marks-Schiller","product_price":8,"product_stock_count":1},
{"product_id":2,"product_name":"Huel-Goodwin","product_price":83,"product_stock_count":2},
{"product_id":3,"product_name":"Bogan-Heidenreich","product_price":59,"product_stock_count":3},
{"product_id":4,"product_name":"O'Conner LLC","product_price":42,"product_stock_count":4},
{"product_id":5,"product_name":"Bergnaum, Oberbrunner and Howell","product_price":8,"product_stock_count":5},
{"product_id":6,"product_name":"Hintz LLC","product_price":13,"product_stock_count":6},
{"product_id":7,"product_name":"Price-Bednar","product_price":3,"product_stock_count":7},
{"product_id":8,"product_name":"Wolff Group","product_price":33,"product_stock_count":8},
{"product_id":9,"product_name":"Collier-White","product_price":80,"product_stock_count":9},
{"product_id":10,"product_name":"Bogan-Emmerich","product_price":37,"product_stock_count":10},
{"product_id":11,"product_name":"Ankunding Group","product_price":51,"product_stock_count":11},
{"product_id":12,"product_name":"Pagac Inc","product_price":19,"product_stock_count":12},
{"product_id":13,"product_name":"Doyle, Wilkinson and Ryan","product_price":20,"product_stock_count":13},
{"product_id":14,"product_name":"Reichel Group","product_price":42,"product_stock_count":14},
{"product_id":15,"product_name":"Williamson, Armstrong and Cremin","product_price":73,"product_stock_count":15},
{"product_id":16,"product_name":"Franecki Inc","product_price":5,"product_stock_count":16},
{"product_id":17,"product_name":"Sanford-Schaden","product_price":62,"product_stock_count":17},
{"product_id":18,"product_name":"Watsica-Kilback","product_price":14,"product_stock_count":18},
{"product_id":19,"product_name":"Waelchi-Hessel","product_price":7,"product_stock_count":19},
{"product_id":20,"product_name":"Dare, Streich and Heathcote","product_price":53,"product_stock_count":20},
{"product_id":21,"product_name":"Thiel, Wehner and Wolff","product_price":69,"product_stock_count":21},
{"product_id":22,"product_name":"Powlowski Group","product_price":31,"product_stock_count":22},
{"product_id":23,"product_name":"Waters Group","product_price":52,"product_stock_count":23},
{"product_id":24,"product_name":"Pacocha LLC","product_price":85,"product_stock_count":24},
{"product_id":25,"product_name":"Pollich-Farrell","product_price":82,"product_stock_count":25},
{"product_id":26,"product_name":"Lowe-Yost","product_price":16,"product_stock_count":26},
{"product_id":27,"product_name":"Goyette Group","product_price":3,"product_stock_count":27},
{"product_id":28,"product_name":"Stokes-Erdman","product_price":74,"product_stock_count":28},
{"product_id":29,"product_name":"Heaney-Pfannerstill","product_price":17,"product_stock_count":29},
{"product_id":30,"product_name":"Ziemann-Murphy","product_price":25,"product_stock_count":30},
{"product_id":31,"product_name":"Thompson-Quigley","product_price":26,"product_stock_count":31},
{"product_id":32,"product_name":"Yost, Jaskolski and Marquardt","product_price":92,"product_stock_count":32},
{"product_id":33,"product_name":"Harris and Sons","product_price":81,"product_stock_count":33},
{"product_id":34,"product_name":"Tromp, Cremin and Graham","product_price":98,"product_stock_count":34},
{"product_id":35,"product_name":"Johns, Ebert and Bradtke","product_price":74,"product_stock_count":35},
{"product_id":36,"product_name":"Mayert, Larkin and Osinski","product_price":78,"product_stock_count":36},
{"product_id":37,"product_name":"Paucek, Marvin and Simonis","product_price":81,"product_stock_count":37},
{"product_id":38,"product_name":"Ledner-Feest","product_price":84,"product_stock_count":38},
{"product_id":39,"product_name":"Terry, Jerde and Cremin","product_price":28,"product_stock_count":39},
{"product_id":40,"product_name":"Monahan Group","product_price":39,"product_stock_count":40},
{"product_id":41,"product_name":"Grant-Towne","product_price":43,"product_stock_count":41},
{"product_id":42,"product_name":"Will-McCullough","product_price":53,"product_stock_count":42},
{"product_id":43,"product_name":"Price, Boyer and Hettinger","product_price":52,"product_stock_count":43},
{"product_id":44,"product_name":"Bechtelar Group","product_price":97,"product_stock_count":44},
{"product_id":45,"product_name":"Corwin and Sons","product_price":18,"product_stock_count":45},
{"product_id":46,"product_name":"Paucek Group","product_price":96,"product_stock_count":46},
{"product_id":47,"product_name":"Rohan and Sons","product_price":21,"product_stock_count":47},
{"product_id":48,"product_name":"Wisozk LLC","product_price":11,"product_stock_count":48},
{"product_id":49,"product_name":"Graham-Heidenreich","product_price":62,"product_stock_count":49},
{"product_id":50,"product_name":"Nolan, Considine and Bashirian","product_price":98,"product_stock_count":50},
{"product_id":51,"product_name":"Hamill, Bins and Mayert","product_price":18,"product_stock_count":51},
{"product_id":52,"product_name":"Pollich-Rice","product_price":80,"product_stock_count":52},
{"product_id":53,"product_name":"Stehr LLC","product_price":70,"product_stock_count":53},
{"product_id":54,"product_name":"Jones-Satterfield","product_price":8,"product_stock_count":54},
{"product_id":55,"product_name":"Macejkovic, Fay and Hickle","product_price":49,"product_stock_count":55},
{"product_id":56,"product_name":"Bosco, Reichert and Kertzmann","product_price":67,"product_stock_count":56},
{"product_id":57,"product_name":"Lindgren-Kreiger","product_price":85,"product_stock_count":57},
{"product_id":58,"product_name":"Greenfelder-Predovic","product_price":92,"product_stock_count":58},
{"product_id":59,"product_name":"Labadie, Cronin and Shields","product_price":7,"product_stock_count":59},
{"product_id":60,"product_name":"Bahringer LLC","product_price":49,"product_stock_count":60},
{"product_id":61,"product_name":"Buckridge Inc","product_price":41,"product_stock_count":61},
{"product_id":62,"product_name":"Renner LLC","product_price":44,"product_stock_count":62},
{"product_id":63,"product_name":"Douglas-Predovic","product_price":36,"product_stock_count":63},
{"product_id":64,"product_name":"Carter, Dickens and Berge","product_price":71,"product_stock_count":64},
{"product_id":65,"product_name":"Bode, Beier and Daniel","product_price":35,"product_stock_count":65},
{"product_id":66,"product_name":"Waters, Runolfsson and Krajcik","product_price":27,"product_stock_count":66},
{"product_id":67,"product_name":"Rolfson, Goldner and Kihn","product_price":21,"product_stock_count":67},
{"product_id":68,"product_name":"White Inc","product_price":22,"product_stock_count":68},
{"product_id":69,"product_name":"Willms, Abernathy and Mayert","product_price":64,"product_stock_count":69},
{"product_id":70,"product_name":"Conn-Heller","product_price":64,"product_stock_count":70},
{"product_id":71,"product_name":"Gusikowski Inc","product_price":25,"product_stock_count":71},
{"product_id":72,"product_name":"Bode-Morissette","product_price":39,"product_stock_count":72},
{"product_id":73,"product_name":"Moen Inc","product_price":20,"product_stock_count":73},
{"product_id":74,"product_name":"Wehner Group","product_price":79,"product_stock_count":74},
{"product_id":75,"product_name":"Gerhold-Lindgren","product_price":6,"product_stock_count":75},
{"product_id":76,"product_name":"Fadel-Rutherford","product_price":56,"product_stock_count":76},
{"product_id":77,"product_name":"Schulist Group","product_price":81,"product_stock_count":77},
{"product_id":78,"product_name":"Douglas, Reichert and Kuhlman","product_price":44,"product_stock_count":78},
{"product_id":79,"product_name":"Deckow, Miller and Cruickshank","product_price":78,"product_stock_count":79},
{"product_id":80,"product_name":"Stiedemann, Brakus and Wisozk","product_price":35,"product_stock_count":80},
{"product_id":81,"product_name":"Kuphal, Stamm and Wuckert","product_price":89,"product_stock_count":81},
{"product_id":82,"product_name":"Kirlin, Schulist and Nader","product_price":10,"product_stock_count":82},
{"product_id":83,"product_name":"Bayer-Johns","product_price":100,"product_stock_count":83},
{"product_id":84,"product_name":"Baumbach, McCullough and Baumbach","product_price":26,"product_stock_count":84},
{"product_id":85,"product_name":"Kuhic Group","product_price":43,"product_stock_count":85},
{"product_id":86,"product_name":"Hermiston LLC","product_price":73,"product_stock_count":86},
{"product_id":87,"product_name":"Zieme, Davis and Ortiz","product_price":2,"product_stock_count":87},
{"product_id":88,"product_name":"Kassulke, Jones and Schmitt","product_price":10,"product_stock_count":88},
{"product_id":89,"product_name":"Farrell, Corkery and Ratke","product_price":97,"product_stock_count":89},
{"product_id":90,"product_name":"Wiegand, Robel and O'Hara","product_price":25,"product_stock_count":90},
{"product_id":91,"product_name":"Schuster LLC","product_price":92,"product_stock_count":91},
{"product_id":92,"product_name":"Strosin, Lehner and Muller","product_price":81,"product_stock_count":92},
{"product_id":93,"product_name":"Zieme and Sons","product_price":75,"product_stock_count":93},
{"product_id":94,"product_name":"Lebsack, Carter and Goodwin","product_price":88,"product_stock_count":94},
{"product_id":95,"product_name":"Zemlak, Hayes and Deckow","product_price":43,"product_stock_count":95},
{"product_id":96,"product_name":"Walsh Group","product_price":47,"product_stock_count":96},
{"product_id":97,"product_name":"Wilkinson Group","product_price":4,"product_stock_count":97},
{"product_id":98,"product_name":"Roberts-Dare","product_price":4,"product_stock_count":98},
{"product_id":99,"product_name":"Lesch Group","product_price":89,"product_stock_count":99},
{"product_id":100,"product_name":"Walter LLC","product_price":29,"product_stock_count":100}]