/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ITask } from "./components/tasks/tasks";
import { IUser } from "./components/users/users";
export namespace Components {
    interface AppRoot {
    }
    interface HomeComponent {
    }
    interface TaskComponent {
        "task": ITask;
    }
    interface TasksComponent {
    }
    interface UsersComponent {
        "users": Array<IUser>;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHomeComponentElement extends Components.HomeComponent, HTMLStencilElement {
    }
    var HTMLHomeComponentElement: {
        prototype: HTMLHomeComponentElement;
        new (): HTMLHomeComponentElement;
    };
    interface HTMLTaskComponentElement extends Components.TaskComponent, HTMLStencilElement {
    }
    var HTMLTaskComponentElement: {
        prototype: HTMLTaskComponentElement;
        new (): HTMLTaskComponentElement;
    };
    interface HTMLTasksComponentElement extends Components.TasksComponent, HTMLStencilElement {
    }
    var HTMLTasksComponentElement: {
        prototype: HTMLTasksComponentElement;
        new (): HTMLTasksComponentElement;
    };
    interface HTMLUsersComponentElement extends Components.UsersComponent, HTMLStencilElement {
    }
    var HTMLUsersComponentElement: {
        prototype: HTMLUsersComponentElement;
        new (): HTMLUsersComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "home-component": HTMLHomeComponentElement;
        "task-component": HTMLTaskComponentElement;
        "tasks-component": HTMLTasksComponentElement;
        "users-component": HTMLUsersComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface HomeComponent {
    }
    interface TaskComponent {
        "task"?: ITask;
    }
    interface TasksComponent {
    }
    interface UsersComponent {
        "users"?: Array<IUser>;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "home-component": HomeComponent;
        "task-component": TaskComponent;
        "tasks-component": TasksComponent;
        "users-component": UsersComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "home-component": LocalJSX.HomeComponent & JSXBase.HTMLAttributes<HTMLHomeComponentElement>;
            "task-component": LocalJSX.TaskComponent & JSXBase.HTMLAttributes<HTMLTaskComponentElement>;
            "tasks-component": LocalJSX.TasksComponent & JSXBase.HTMLAttributes<HTMLTasksComponentElement>;
            "users-component": LocalJSX.UsersComponent & JSXBase.HTMLAttributes<HTMLUsersComponentElement>;
        }
    }
}
